name: how_to_cook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.7
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  focus_detector: ^2.0.1
  http: ^1.2.2
  injector: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  translator: ^1.0.3+1
  url_launcher: ^6.3.1
  world_flags: ^1.1.1
  fraction: ^3.0.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

fonts:
    - family: Comfortaa
      fonts:
        - asset: assets\fonts\Comfortaa-300.ttf
          weight: 300
        - asset: assets\fonts\Comfortaa-400.ttf
          weight: 400
        - asset: assets\fonts\Comfortaa-500.ttf
          weight: 500
        - asset: assets\fonts\Comfortaa-600.ttf
          weight: 600
        - asset: assets\fonts\Comfortaa-700.ttf
          weight: 700
